from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
import re

PLSFIX_RE = re.compile(r"\bpls\s*fix\b|\bplsfix\b|\bplease\s+fix\b", re.IGNORECASE)
DIAGNOSTIC_BUNDLE_HOURS = 6
RECENT_ROW_LIMIT = 24


@dataclass(slots=True)
class DiagnosticRequest:
    guild_id: int | None
    channel_id: int
    user_id: int
    message_id: int
    message_url: str
    prompt: str


def is_plsfix_request(prompt: str) -> bool:
    return bool(PLSFIX_RE.search(prompt))


async def send_plsfix_diagnostics(
    bot,
    *,
    database,
    settings,
    request: DiagnosticRequest,
    now: datetime | None = None,
) -> bool:
    from nycti.error_debug import send_error_debug_message

    if settings.error_debug_channel_id is None:
        return False
    captured_at = now or datetime.now(timezone.utc)
    bundle = await build_plsfix_diagnostic_bundle(
        database,
        request=request,
        captured_at=captured_at,
        hours=DIAGNOSTIC_BUNDLE_HOURS,
    )
    content = (
        "```text\n"
        "nycti_plsfix_bundle\n"
        f"source_channel_id: {request.channel_id}\n"
        f"source_message_id: {request.message_id}\n"
        f"source_user_id: {request.user_id}\n"
        f"source_message_url: {request.message_url}\n"
        f"window_hours: {DIAGNOSTIC_BUNDLE_HOURS}\n"
        "attachment: recent diagnostic bundle for Codex\n"
        "```"
    )
    await send_error_debug_message(
        bot,
        channel_id=settings.error_debug_channel_id,
        content=content,
        attachment_text=bundle,
        attachment_filename=f"nycti-plsfix-{request.message_id}.txt",
    )
    return True


async def build_plsfix_diagnostic_bundle(
    database,
    *,
    request: DiagnosticRequest,
    captured_at: datetime,
    hours: int = DIAGNOSTIC_BUNDLE_HOURS,
) -> str:
    from sqlalchemy import desc, select

    from nycti.db.models import AgentStepEvent, MessageDebugEvent, ToolCallEvent
    from nycti.discord.logs import build_usage_logs_snapshot, format_usage_logs_report

    since = captured_at - timedelta(hours=hours)
    async with database.session() as session:
        snapshot = await build_usage_logs_snapshot(session, since=since, guild_id=request.guild_id)
        usage_report = format_usage_logs_report(
            snapshot,
            window_label=f"last {hours}h",
            now=captured_at,
        )
        agent_steps = (
            await session.execute(
                select(AgentStepEvent)
                .where(
                    AgentStepEvent.created_at >= since,
                    AgentStepEvent.guild_id == request.guild_id,
                )
                .order_by(desc(AgentStepEvent.created_at))
                .limit(RECENT_ROW_LIMIT)
            )
        ).scalars().all()
        tool_calls = (
            await session.execute(
                select(ToolCallEvent)
                .where(
                    ToolCallEvent.created_at >= since,
                    ToolCallEvent.guild_id == request.guild_id,
                )
                .order_by(desc(ToolCallEvent.created_at))
                .limit(RECENT_ROW_LIMIT)
            )
        ).scalars().all()
        message_debug_events = (
            await session.execute(
                select(MessageDebugEvent)
                .where(
                    MessageDebugEvent.created_at >= since,
                    MessageDebugEvent.guild_id == request.guild_id,
                )
                .order_by(desc(MessageDebugEvent.created_at))
                .limit(RECENT_ROW_LIMIT)
            )
        ).scalars().all()

    lines = [
        "nycti_plsfix_diagnostic_bundle",
        f"captured_at: {captured_at.isoformat()}",
        f"window_start: {since.isoformat()}",
        f"guild_id: {request.guild_id}",
        f"source_channel_id: {request.channel_id}",
        f"source_message_id: {request.message_id}",
        f"source_user_id: {request.user_id}",
        f"source_message_url: {request.message_url}",
        f"prompt: {_one_line(request.prompt, 500)}",
        "",
        "usage_summary",
        usage_report,
        "",
        "recent_agent_steps",
        *_format_agent_steps(agent_steps),
        "",
        "recent_tool_calls",
        *_format_tool_calls(tool_calls),
        "",
        "recent_message_debug_timings",
        *_format_message_debug_events(message_debug_events),
        "",
        "notes",
        "- This bundle is generated by @Nycti plsfix and contains DB-backed operational telemetry only.",
        "- It does not include raw Discord message history or secrets.",
    ]
    return "\n".join(lines)


def _format_agent_steps(rows: list[object]) -> list[str]:
    if not rows:
        return ["(none)"]
    lines = ["time | run | idx | state | feature | model | tool | status | stop | ms | tok"]
    for row in rows:
        lines.append(
            " | ".join(
                [
                    _time(row.created_at),
                    row.run_id[:8],
                    str(row.step_index),
                    row.state,
                    row.feature or "",
                    _compact_model(row.active_model or row.requested_model or ""),
                    row.tool_name or "",
                    row.status or "",
                    row.stop_reason or "",
                    str(row.latency_ms),
                    str(row.total_tokens),
                ]
            )
        )
    return lines


def _format_tool_calls(rows: list[object]) -> list[str]:
    if not rows:
        return ["(none)"]
    lines = ["time | tool | status | ms | channel | user"]
    for row in rows:
        lines.append(
            f"{_time(row.created_at)} | {row.tool_name} | {row.status} | "
            f"{row.latency_ms} | {row.channel_id or ''} | {row.user_id or ''}"
        )
    return lines


def _format_message_debug_events(rows: list[object]) -> list[str]:
    if not rows:
        return ["(none)"]
    lines = ["time | part | ms | source_message | channel | user"]
    for row in rows:
        lines.append(
            f"{_time(row.created_at)} | {row.part} | {row.latency_ms} | "
            f"{row.source_message_id or ''} | {row.channel_id or ''} | {row.user_id or ''}"
        )
    return lines


def _time(value: datetime) -> str:
    return value.astimezone(timezone.utc).strftime("%m-%d %H:%M:%S")


def _compact_model(model: str) -> str:
    if not model:
        return ""
    if "/models/" in model:
        model = model.rsplit("/models/", 1)[-1]
    if "/" in model:
        model = model.rsplit("/", 1)[-1]
    return model[:32]


def _one_line(value: str, limit: int) -> str:
    cleaned = " ".join(value.replace("```", "'''").split())
    if len(cleaned) <= limit:
        return cleaned
    return cleaned[: limit - 3].rstrip() + "..."
