from __future__ import annotations

from pathlib import Path
from typing import Any

from nycti.benchmarks import EARNINGS_BENCHMARK_PROMPT
from nycti.chat.context import build_user_prompt
from nycti.chat.orchestrator_support import format_available_tool_guidance
from nycti.chat.tool_eligibility import select_eligible_tools
from nycti.chat.tools.schemas import build_chat_tools
from nycti.prompts import get_system_prompt


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "example_prompt.md"


def generate_example_prompt() -> str:
    eligible_tool_names, _permissions = select_eligible_tools(
        request_text=EARNINGS_BENCHMARK_PROMPT,
        guild_id=1448835634725912738,
    )
    tools = build_chat_tools(eligible_tool_names)
    available_tool_names = _tool_names(tools)
    user_prompt = build_user_prompt(
        user_name="jacen",
        user_id=266241639003979776,
        user_global_name="jacen",
        owner_context="The current user is the configured bot owner/admin.",
        current_datetime_text=(
            "Current UTC date/time: 2026-06-13 18:42 UTC\n"
            "Current local date/time for the user: 2026-06-13 11:42 America/Los_Angeles"
        ),
        prompt=EARNINGS_BENCHMARK_PROMPT,
        context_block="jacen: benchmark earnings\nNycti: Running benchmark...",
        extended_context_block="(not requested yet; use `channel_ctx` if older Discord context is needed)",
        image_context_block="(no included images)",
        vision_context_block="(no image analysis)",
        personal_profile_block="- prefers concise technical debugging\n- works on Nycti",
        memories_block="- [preference] User prefers direct answers and concrete debugging details.",
        channel_alias_block="(none configured)",
        member_alias_block="(none matched)",
        mentioned_user_memories_block="(none)",
    )
    tool_guidance = format_available_tool_guidance(available_tool_names=available_tool_names)
    names_block = "\n".join(sorted(available_tool_names))
    schema_block = _format_tool_schema_summary(tools)
    return (
        "# Example Nycti Prompt Payload\n\n"
        "Generated by `PYTHONPATH=src python3 scripts/generate_example_prompt.py`.\n\n"
        "This is a sanitized example of the full prompt shape Nycti sends for a normal triggered chat reply. "
        "The provider request is not one giant system prompt: it is a `system` message, a large `user` "
        "context message, one appended tool-policy `user` message, and a separate native `tools` schema array.\n\n"
        "## Message 1: system\n\n"
        f"```text\n{get_system_prompt()}\n```\n\n"
        "## Message 2: user context\n\n"
        f"```text\n{user_prompt}\n```\n\n"
        "## Message 3: available-tool guidance\n\n"
        f"```text\n{tool_guidance}\n```\n\n"
        "## Native tools array\n\n"
        "The provider request includes every read-only tool. Mutating action tools are included only when the "
        "request explicitly authorizes them. "
        "The exposed tool names are:\n\n"
        f"```text\n{names_block}\n```\n\n"
        "Schema summary:\n\n"
        f"```text\n{schema_block}\n```\n"
    )


def _format_tool_schema_summary(tools: list[dict[str, object]]) -> str:
    blocks: list[str] = []
    for tool in tools:
        function = tool.get("function")
        if not isinstance(function, dict):
            continue
        name = function.get("name")
        parameters = function.get("parameters")
        if not isinstance(name, str) or not isinstance(parameters, dict):
            continue
        properties = parameters.get("properties")
        required = parameters.get("required")
        lines = [f"{name}:"]
        if isinstance(required, list) and required:
            lines.append("  required: " + ", ".join(str(item) for item in required))
        if isinstance(properties, dict):
            for property_name, spec in properties.items():
                if isinstance(spec, dict):
                    lines.append(f"  {_format_property_line(str(property_name), spec)}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)


def _tool_names(tools: list[dict[str, object]]) -> set[str]:
    names: set[str] = set()
    for tool in tools:
        function = tool.get("function")
        if not isinstance(function, dict):
            continue
        name = function.get("name")
        if isinstance(name, str) and name:
            names.add(name)
    return names


def _format_property_line(name: str, spec: dict[str, Any]) -> str:
    type_name = str(spec.get("type", "object"))
    if type_name == "array":
        item_spec = spec.get("items")
        item_type = item_spec.get("type", "object") if isinstance(item_spec, dict) else "object"
        type_name = f"{item_type}[]"
    details: list[str] = []
    if "maxItems" in spec:
        details.append(f"max {spec['maxItems']}")
    if "minimum" in spec or "maximum" in spec:
        details.append(f"{spec.get('minimum', '?')}-{spec.get('maximum', '?')}")
    if "enum" in spec and isinstance(spec["enum"], list):
        details.append(" | ".join(str(item) for item in spec["enum"]))
    suffix = f" ({'; '.join(details)})" if details else ""
    return f"{name}: {type_name}{suffix}"


def main() -> None:
    OUTPUT_PATH.write_text(generate_example_prompt(), encoding="utf-8")


if __name__ == "__main__":
    main()
